# Site Settings

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

title: "Kassidy Flick"
description: "Computer Science portfolio featuring projects, coursework, and professional development."

# Plugins

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache