# Site Settings

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "catppuccin_mocha"

title: "kflick3r's homepage"
description: "Bookmark this to keep an eye on my project updates!"

# Plugins

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache